[package]
name = "hc_zome_mere_memory"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"
license = "CAL-1.0"
repository = "https://github.com/spartan-holochain-counsel/hc-zome-mere-memory"
description = ""
readme = "README.md"

[lib]
name = "mere_memory_api"
crate-type = ["cdylib", "rlib"]

[dependencies]
mere_memory = {path = "./mere_memory"}
mere_memory_types = {path = "./mere_memory_types"}
hdk = "0.3.0-beta-dev.41"
serde = "1"
